---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  changed_when: false
- name: Ensure InfluxDB is installed.
  apt:
    name: influxdb
    state: installed
- name: Copy InfluxDB configuration
  template: src=influxdb.conf dest=/etc/influxdb/influxdb.conf
- name: Install SSL cert for influxdb
  copy:
    content: '{{ ssl_key_and_certificate_combined }}'
    dest: /etc/ssl/influxdb.pem
    owner: root
    group: root
    mode: 0644
  no_log: true
  notify: restart influxdb
- name: Sets the message of the day
  template: src=motd dest=/etc/motd
